title: Brandi Rodriguez
#logo: /assets/img/headshot_circle.png
#logo: /assets/headshot_circle.png
#description: text below image
show_downloads: false 
#theme: jekyll-theme-minimal
#theme: jekyll-theme-cayman
remote_theme: mmistakes/minimal-mistakes
remote_theme: remote_theme: kralizek/minimal-mistakes

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/brandinicole"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/brandirodriguez37"
