title: Brandi Rodriguez
#logo: /assets/img/headshot_circle.png
#logo: /assets/headshot_circle.png
#description: text below image
show_downloads: false 
#theme: jekyll-theme-minimal
theme: jekyll-theme-cayman
