title: Brandi Rodriguez
#logo: /assets/img/headshot_circle.png
logo: /assets/img/headshot_circle.png
#description: text below image
show_downloads: false 
theme: jekyll-theme-minimal


footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/brandinicole210"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/brandirodriguez37"
